"""Add is_vip to User

Revision ID: 3968b3e3983a
Revises: 74cf70dd7cd8
Create Date: 2025-08-31 01:37:19.631805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3968b3e3983a'
down_revision = '74cf70dd7cd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_vip', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_vip')

    # ### end Alembic commands ###
