"""Adiciona Templog, contrato e uploads de documentos

Revision ID: 844b8edebfae
Revises: b084bca35d0b
Create Date: 2025-08-28 23:17:16.859321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '844b8edebfae'
down_revision = 'b084bca35d0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
