"""Add reservation_date to Reservation model

Revision ID: a7ddbb7f7ebc
Revises: d36e540273cd
Create Date: 2025-09-02 00:22:24.108707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7ddbb7f7ebc'
down_revision = 'd36e540273cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reservation_date', sa.Date(), nullable=False))
        batch_op.create_index(batch_op.f('ix_reservation_reservation_date'), ['reservation_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reservation_reservation_date'))
        batch_op.drop_column('reservation_date')

    # ### end Alembic commands ###
