"""Add contract_accepted to User model

Revision ID: b084bca35d0b
Revises: efd6a33e8cad
Create Date: 2025-08-28 22:37:11.004316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b084bca35d0b'
down_revision = 'efd6a33e8cad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('contract_accepted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'contract_accepted')
    # ### end Alembic commands ###
