"""Add video tutorial fields to Room model

Revision ID: d36e540273cd
Revises: fe48ecc0cfde
Create Date: 2025-09-01 23:24:40.336692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd36e540273cd'
down_revision = 'fe48ecc0cfde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_tutorial_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('video_tutorial_autoclave_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('video_tutorial_raiox_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('video_tutorial_plastificadora_url', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_column('video_tutorial_plastificadora_url')
        batch_op.drop_column('video_tutorial_raiox_url')
        batch_op.drop_column('video_tutorial_autoclave_url')
        batch_op.drop_column('video_tutorial_url')

    # ### end Alembic commands ###
