"""Adiciona status is_active ao usuario

Revision ID: e5c40ab0b736
Revises: 844b8edebfae
Create Date: 2025-08-29 08:46:08.965294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5c40ab0b736'
down_revision = '844b8edebfae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('1')))
    op.drop_column('user', 'contract_accepted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('contract_accepted', sa.BOOLEAN(), nullable=True))
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###
