"""Criacao inicial de todas as tabelas

Revision ID: efd6a33e8cad
Revises: 
Create Date: 2025-08-28 22:30:03.978648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efd6a33e8cad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('parking_spot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('rentable_equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('daily_price', sa.Float(), nullable=False),
    sa.Column('units_available', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('video_url', sa.String(length=255), nullable=True),
    sa.Column('price_2h30', sa.Float(), nullable=False),
    sa.Column('price_1h15', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('admin_notice', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('tutorial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('video_url', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_completo', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('cro', sa.String(length=20), nullable=False),
    sa.Column('uf_cro', sa.String(length=2), nullable=False),
    sa.Column('whatsapp', sa.String(length=20), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('genero', sa.String(length=50), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('is_vip', sa.Boolean(), nullable=True),
    sa.Column('is_chato', sa.Boolean(), nullable=True),
    sa.Column('fobs_balance', sa.Float(), nullable=True),
    sa.Column('contract_accepted_version', sa.Integer(), nullable=True),
    sa.Column('veiculo_modelo', sa.String(length=100), nullable=True),
    sa.Column('veiculo_placa', sa.String(length=10), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('selfie_filename', sa.String(length=255), nullable=True),
    sa.Column('document_filename', sa.String(length=255), nullable=True),
    sa.Column('signature_filename', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('cro'),
    sa.UniqueConstraint('whatsapp')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('api_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_log_event_type'), 'api_log', ['event_type'], unique=False)
    op.create_index(op.f('ix_api_log_status'), 'api_log', ['status'], unique=False)
    op.create_index(op.f('ix_api_log_timestamp'), 'api_log', ['timestamp'], unique=False)
    op.create_table('equipment_reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservation_date', sa.Date(), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['rentable_equipment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_reservation_reservation_date'), 'equipment_reservation', ['reservation_date'], unique=False)
    op.create_table('parking_reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservation_date', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('spot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['spot_id'], ['parking_spot.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parking_reservation_reservation_date'), 'parking_reservation', ['reservation_date'], unique=False)
    op.create_table('reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservation_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservation_is_paid'), 'reservation', ['is_paid'], unique=False)
    op.create_index(op.f('ix_reservation_reservation_date'), 'reservation', ['reservation_date'], unique=False)
    op.create_table('room_equipment',
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room_equipment')
    op.drop_index(op.f('ix_reservation_reservation_date'), table_name='reservation')
    op.drop_index(op.f('ix_reservation_is_paid'), table_name='reservation')
    op.drop_table('reservation')
    op.drop_index(op.f('ix_parking_reservation_reservation_date'), table_name='parking_reservation')
    op.drop_table('parking_reservation')
    op.drop_index(op.f('ix_equipment_reservation_reservation_date'), table_name='equipment_reservation')
    op.drop_table('equipment_reservation')
    op.drop_index(op.f('ix_api_log_timestamp'), table_name='api_log')
    op.drop_index(op.f('ix_api_log_status'), table_name='api_log')
    op.drop_index(op.f('ix_api_log_event_type'), table_name='api_log')
    op.drop_table('api_log')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('tutorial')
    op.drop_table('site_settings')
    op.drop_table('room')
    op.drop_table('rentable_equipment')
    op.drop_table('parking_spot')
    op.drop_table('equipment')
    # ### end Alembic commands ###
