"""Add default prices functionality

Revision ID: fe48ecc0cfde
Revises: d5732ad3cbf3
Create Date: 2025-09-01 20:35:37.595087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe48ecc0cfde'
down_revision = 'd5732ad3cbf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_equipment',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.PrimaryKeyConstraint('room_id', 'equipment_id')
    )
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_1h15', sa.Float(), nullable=False))

    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value', sa.Text(), nullable=True))
        batch_op.drop_column('contact_email')
        batch_op.drop_column('site_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_name', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('contact_email', sa.VARCHAR(length=128), nullable=True))
        batch_op.drop_column('value')

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_column('price_1h15')

    op.drop_table('room_equipment')
    # ### end Alembic commands ###
